language: python

python:
  - 3.6

cache: pip

env:
  - MONGO_URI=mongodb://localhost/events

services:
  - mongodb

install:
  - pip install -r app/requirements.txt

script:
  - flake8 app
  - nosetests app
