language: python

python:
  - 3.6

cache: pip

env:
  global:
    - MONGO_URI=mongodb://localhost/events
    - REDIS_HOST=localhost

services:
  - mongodb
  - redis-server

install:
  - pip install -r app/requirements.txt

script:
  - flake8 app
  - nosetests app
