version: '3'

services:

  nginx:
    restart: always
    image: nginx:1.15
    ports:
      - "5000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - app:app
    command: /bin/bash -c "nginx -g 'daemon off;'"

  redis:
    restart: always
    image: redis:4.0

  app:
    restart: always
    build: .
    links:
      - redis:redis
    command: gunicorn --bind 0.0.0.0:5001 datahub.wsgi:app
    deploy:
      replicas: 3
